import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import useLocalStorage from "~/hooks/useLocalStorage";
import { useEffect } from "react";

export default function Home() {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const { value, setValueAndStorage } = useLocalStorage("URL_ID");

  useEffect(() => {
    if (value) {
      void router.push(`/schedule/${value}`);
    }
  }, [value, router]);

  const createMutation = api.url.create.useMutation({
    onError: (error) => {
      console.log(error);
    },
    onSuccess: async (data) => {
      setValueAndStorage(data.id);
      await router.push(`/schedule/${data.id}`);
    },
  });

  const onCreateURL = () => {
    createMutation.mutate({ userId: "" });
  };

  return (
    <>
      <Head>
        <title>OOMAKA | 年間スケジュール、まとめるなら</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight  sm:text-[3rem]">
            年間スケジュール、まとめよう !
          </h1>

          <div className="flex flex-col items-center gap-2">
            <div className="flex flex-col items-center justify-center gap-4">
              <br />
              <button
                className="w-72 rounded-full bg-green-500 px-10 py-3 font-semibold  text-white no-underline transition hover:bg-green-300"
                onClick={onCreateURL}
              >
                新しいカレンダーを作る
              </button>
              <button
                className="my-3 w-72 rounded-full bg-blue-500 px-10 py-3  font-semibold text-white no-underline transition hover:bg-blue-300"
                onClick={() => void signIn()}
              >
                新規アカウントを作る
              </button>

              {sessionData && (
                <button
                  className="my-3 w-72 rounded-full bg-blue-500 px-10 py-3  font-semibold text-white no-underline transition hover:bg-blue-300"
                  onClick={() => void signIn()}
                >
                  ログイン
                </button>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
