import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import Period from "~/features/schedules/components/Period";
import Items from "~/features/schedules/components/Items";
import { api } from "~/utils/api";
import dayjs from "~/utils/dayjs";
import { monthItems, getScheduleInMonth } from "~/utils/schedule";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  const schedules = api.schedule.fetch.useQuery({ urlId: String(id) });
  const months = monthItems(
    Number(dayjs().format("M")),
    Number(dayjs().year())
  );

  return (
    <>
      <Head>
        <title>OMAKA | 年間スケジュール、まとめるなら</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto max-w-screen-xl gap-12 px-4  pt-3 ">
        <div>
          <Period
            startDate={dayjs().format()}
            endDate={dayjs().add(1, "years").format()}
          />
        </div>
        <div className="flex flex-col flex-nowrap justify-center pt-10 sm:flex-row sm:flex-wrap sm:justify-start">
          {schedules.isLoading ? (
            <div className="flex h-screen w-screen items-center justify-center">
              loading...
            </div>
          ) : (
            months.map((item, index) => (
              <div key={index} className="px-8 pb-8 sm:pb-16">
                <Items
                  urlId={String(id)}
                  date={item}
                  defaultItems={getScheduleInMonth(item, schedules.data ?? [])}
                />
              </div>
            ))
          )}
        </div>
      </main>
    </>
  );
}
